name: Build and Deploy

on:
  push:
    branches: [ main ] # 當您推送程式碼到 main 分支時觸發
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pnpm
        uses: pnpm/action-setup@v4 # 這裡改用新版 setup
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro
        run: pnpm run build

      - name: Upload artifact
        if: github.event_name == 'push' # 只有正式 push 時才上傳檔案準備部署
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: check
    runs-on: ubuntu-latest
    name: Deploy to Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4